I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/chapter1_checkin.rpy", line 5, in script
    show tom neutralhumanmask at right
Exception: Image 'tom' does not accept attributes 'neutralhumanmask'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/chapter1_checkin.rpy", line 5, in script
    show tom neutralhumanmask at right
  File "renpy/ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1378, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 397, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 267, in extraneous
    " ".join(self.args),
Exception: Image 'tom' does not accept attributes 'neutralhumanmask'.

Windows-10-10.0.19041 AMD64
Ren'Py 7.5.1.22070801
The Waiting Room 1.0
Sat Jul 23 21:16:28 2022
